services:
  nginx:
    image: nginx:stable-alpine3.21-perl
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "6566:80"
      - "6567:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
      - ./html:/usr/share/nginx/html:ro
    environment:
      - TZ=UTC
    networks:
      - nginx-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  nginx-network:
    name: nginx-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16